# Generated by Django 3.2 on 2022-09-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(default=True, max_length=500),
            preserve_default=False,
        ),
    ]
